config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]
  resources :microposts, only: [:create, :destroy, :index, :edit, :update, :show], path: 'artworks'
  resources :relationships, only: [:create, :destroy]
  resources :user_details, only: [:edit, :update], path: 'profile'

  resources :conversations do
    resources :messages
  end

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'static_pages#home'

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :involving, -> (user) do
    where("conversations.sender_id=? OR conversations.recipient_id=?",
              user.id, user.id)
  end

  scope :between, -> (sender_id, recipient_id) do
    where("(conversations.sender_id=? AND conversations.recipient_id=?)
              OR (conversations.sender_id=? AND conversations.recipient_id=?)",
                  sender_id, recipient_id, recipient_id, sender_id)
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :logged_in_user

  layout false, except: :index

  def create
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id],params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end

    render json: { conversation_id: @conversation.id }
  end

  def show
    @conversation = Conversation.find(params[:id])
    @reciever = interlocutor(@conversation)
    @messages = @conversation.messages
    @message = Message.new
  end

  def index
    @conversations = Conversation.involving(current_user)
  end

  def destroy
    Conversation.find(params[:id]).destroy
    flash[:success] = "Conversation deleted"
    redirect_to conversations_path
  end

  private

    def conversation_params
      params.permit(:sender_id, :recipient_id)
    end

    def interlocutor(conversation)
      current_user == conversation.recipient ? conversation.sender : conversation.recipient
    end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/index.html.erb
<% provide(:title, 'All Conversations') %>
<div class="row">
	<h1>Active Conversations</h1>
	<br>
</div>
<h1>Your conversations</h1>
<br>
<% @conversations.each do |conversation| %>
	<ul class="w3-ul w3-card-4">
		<li class="w3-padding-16">
				<button class="w3-btn w3-right w3-round -xxlarge"><%= link_to "delete", conversation, method: :delete, data: { confirm: "You sure?"} %></button>

			<class="w3-left w3-circle w3-margin-right" style="width:60px"><%= gravatar_for conversation.recipient %>
			<span class="w3-xlarge"><%= link_to conversation.recipient.name, conversation.recipient %></span><br>
			<%= link_to "Send Message", "#", id: "chat-artwork", class: "w3-btn w3-round-xlarge w3-green
						start-conversation", "data-sid" => conversation.sender_id,
						"data-rip" => conversation.recipient_id %>
		</li>
	</ul>
<% end %>

app/views/conversations/show.html.erb
<div class="chatboxhead">
  <div class="chatboxtitle">
    <i class="fa fa-comments"></i>

    <h1><%= @reciever.name %> </h1>
  </div>
  <div class="chatboxoptions">
    <%= link_to "<i class='fa  fa-minus'></i> ".html_safe, "#", class: "toggleChatBox", "data-cid" => @conversation.id %>
    &nbsp;&nbsp;
    <%= link_to "<i class='fa  fa-times'></i> ".html_safe, "#", class: "closeChat", "data-cid" => @conversation.id %>
  </div>
  <br clear="all"/>
</div>
<div class="chatboxcontent">
  <% if @messages.any? %>
      <%= render @messages %>
  <% end %>
</div>
<div class="chatboxinput">
  <%= form_for([@conversation, @message], :remote => true, :html => {id: "conversation_form_#{@conversation.id}"}) do |f| %>
      <%= f.text_area :body, class: "chatboxtextarea", "data-cid" => @conversation.id %>
  <% end %>
</div>

<%= subscribe_to conversation_path(@conversation) %>