config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]
  resources :microposts, only: [:create, :destroy, :index, :edit, :update, :show], path: 'artworks'
  resources :relationships, only: [:create, :destroy]
  resources :user_details, only: [:edit, :update], path: 'profile'

  resources :conversations do
    resources :messages
  end

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<footer class= "footer">
	<div class = "container">
		<p>Created by Marx Low and Goh Yi Rui of Team 1211</p>
		<p>Made with Ruby on Rails</p>
		<p>Orbital 2016</p>

		<ul>
			<li><%= link_to "About", about_path %></li>
			<li class="muted">·</li>
			<li><%= link_to "Contact Us", contact_path %></li>
		</ul>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top" link = "black">
		<%= link_to "Artpraiser", root_path, id: "logo" %>
		<nav>
			<ul class = "navbar navbar-nav navbar-right">

				<li class="<%= 'current' if params[:controller] == 'static_pages' %>">
				<%= link_to "Home", root_path %></li>
				<li class="<%= 'current' if params[:controller] == 'users' %>">
				<%= link_to "Artists", users_path %></li>
				<li class="<%= 'current' if params[:controller] == 'microposts' %>">
				<%= link_to "Artworks", microposts_path %></li>
				<% if logged_in? %>
					<li class="<%= 'current' if params[:controller] == 'conversations' %>">
					<%= link_to "Conversations", conversations_path %></li>
					<li class="dropdown">
						<a href='#' class = "dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b>
						</a>
						<ul class="dropdown-menu center">
							<li><%= link_to "Profile", current_user %></li>
							<li><%= link_to "Settings",
									edit_user_detail_path(current_user) %></li>
							<li class="divider"></li>
							<li>
								<%= link_to "Logout", logout_path, method: 'delete' %>
							</li>
						</ul>
				<% else %>
					<li><%= link_to "Login", login_path %></li>
				<% end %>
			</ul>
		</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    'application', media: 'all',
	  							 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application',
	  							 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
		<%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %>

		<meta content='<%= logged_in? ? current_user.id : "" %>' name='user-id'/>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class = "container-fluid">
			<div class = "container">
			<% flash.each do |message_type, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-#{message_type}") %>
			<% end %>
				<%= yield %>
			</div>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
	<% if current_user %>
   	<script type="text/javascript">
        channel = <%= raw ('"' + '/notifications' + current_user.id.to_s + '"') %>
        PrivatePub.subscribe(channel, function(data) {

        var sender_id = data.sid;
        var recipient_id = data.rip;
        var conversation_id = data.cid;

        $.post("/conversations", { sender_id: sender_id, recipient_id: recipient_id }, function (data) {
            chatBox.chatWith(conversation_id);
        });

        });
    </script>
    <%= subscribe_to "/notifications" + current_user.id.to_s %>
    <% end %>
</html>